### ISSUE TITLE
I can't find any "starter documentation" on x/hep/rootio

### ISSUE THREAD

**Issue by jpivarski** [go-hep/hep#112]
The code snippet at the top of the [API documentation](https://godoc.org/go-hep.org/x/hep/rootio) is very terse and contains an error: it reassigns `err` but the inferred type is (now) different between those two lines.

Having found a "Hello, world" Go program on the web to edit, I wrote the following:

```go
package main

import "go-hep.org/x/hep/rootio"
import "fmt"

func main() {
  f, err := rootio.Open("~/storage/data/TrackResonanceNtuple_uncompressed.root")
  obj, err2 := f.Get("twoMuon")
  tree := obj.(*rootio.Tree)
  fmt.Printf("entries= %v\n", t.Entries())
}
```

It fails with

```
% go build test.go
# command-line-arguments
./test.go:9:14: impossible type assertion:
        *rootio.Tree does not implement rootio.Object (missing Class method)
./test.go:10:31: undefined: t
```

(I have Go 1.9 and did `go get go-hep.org/x/hep/rootio` without specifying a version: is it taking master from GitHub or the latest release?)

Is there tutorial-style documentation that I simply haven't found? Are there any minimally working examples? Thanks!

**Comment by sbinet** [comment]
I have fixed the doc typos in go-hep/hep#113.

> (I have Go 1.9 and did go get go-hep.org/x/hep/rootio without specifying a version: is it taking master from GitHub or the latest release?)

yes, `go get` git clones master.

There is no tuto-style documentation for `rootio` yet. sorry.
But there are a few examples:
https://godoc.org/go-hep.org/x/hep/rootio#pkg-examples

especially:
- https://godoc.org/go-hep.org/x/hep/rootio#example-Scanner--WithStruct
- https://godoc.org/go-hep.org/x/hep/rootio#example-Scanner--WithVars
- https://godoc.org/go-hep.org/x/hep/rootio#example-TreeScanner

that deal with iterating over a `rootio.Tree` content.

hth,
-s

**Comment by jpivarski** [comment]
Thanks! That got me started. These auto-generated examples are great, but I didn't find them by casually looking for them. (Perhaps I'd go there first if I were a Go user, I would have the cultural background to expect them to exist.) Could you put a pointer to them at the top of the API documentation? The Scanner examples are the most relevant.

Also, you have a few more typos: the `*` before `rootio.Tree` (I don't know what it means, but it's not there in the Scanner examples and removing it makes the example work) and the `t.Entries()` instead of `tree.Entries()` on the `Printf` line.

Here's a complete working example from me:

```go
package main

import "go-hep.org/x/hep/rootio"
import "fmt"

func main() {
  f, err := rootio.Open("/home/pivarski/storage/data/TrackResonanceNtuple_uncompressed.root")
  obj, err2 := f.Get("twoMuon")
  tree := obj.(rootio.Tree)
  fmt.Printf("entries= %v\n", tree.Entries())

  var (
    mass_mumu float32
    px float32
    py float32
    pz float32
  )
  scanVars := []rootio.ScanVar{
    {Name: "mass_mumu", Value: &mass_mumu},
    {Name: "px", Value: &px},
    {Name: "py", Value: &py},
    {Name: "pz", Value: &pz},
  }

  sc, err3 := rootio.NewScannerVars(tree, scanVars...)

  for sc.Next() {
    err4 := sc.Scan()
    fmt.Printf("%d %v %v %v %v\n", sc.Entry(), mass_mumu, px, py, pz)
    _ = err4
  }

  _ = err
  _ = err2
  _ = err3
}
```

**Comment by sbinet** [comment]
the link to the examples is at the top right of the godoc page: 
https://godoc.org/go-hep.org/x/hep/rootio

(between `Index` and `Files`)

yep, I think I fixed the typos in https://github.com/go-hep/hep/commit/b093b4d454aefb3f8a4f8de3f381eb3295d7dc3e

**Comment by sbinet** [comment]
ah, and a gopher would probably check her error values:

```go
package main

import (
	"fmt"
	"log"

	"go-hep.org/x/hep/rootio"
)

func main() {
	f, err := rootio.Open("/home/pivarski/storage/data/TrackResonanceNtuple_uncompressed.root")
	if err != nil {
		log.Fatal(err)
	}
	obj, ok := f.Get("twoMuon")
	if !ok {
		log.Fatalf("no object twoMuon in file")
	}
	tree := obj.(rootio.Tree)
	fmt.Printf("entries= %v\n", tree.Entries())

	var (
		mass_mumu float32
		px        float32
		py        float32
		pz        float32
	)
	scanVars := []rootio.ScanVar{
		{Name: "mass_mumu", Value: &mass_mumu},
		{Name: "px", Value: &px},
		{Name: "py", Value: &py},
		{Name: "pz", Value: &pz},
	}

	sc, err := rootio.NewScannerVars(tree, scanVars...)
	if err != nil {
		log.Fatal(err)
	}
	defer sc.Close()

	for sc.Next() {
		err := sc.Scan()
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%d %v %v %v %v\n", sc.Entry(), mass_mumu, px, py, pz)
	}
}
```

**Comment by jpivarski** [comment]
> ah, and a gopher would probably check her error values:

I found that on StackOverflow and heartily disagree for a source file I write in `/tmp`. There ought to be some provision for skipping the check on code you intend to throw away minutes in the future. (Probably 70% of the code I write fits that description. I work in `/tmp` a lot.)

> the link to the examples is at the top right of the godoc page:
> https://godoc.org/go-hep.org/x/hep/rootio

Actually, I needed more help than that. That link goes to _all_ the examples, but for this particular project, I need to find an example of reading a TTree before anything else. There are a lot of other things to go through.

It's good that the "examples" link is there, but the intro text should point to the three examples you linked here, specifically. That's what got me started.

I'm closing this because the typos are fixed.
