### ISSUE TITLE
yoda2rio: honor paths in YODA

### ISSUE THREAD

**Issue by lukasheinrich** [go-hep/hep#120]
rigt now yoda2rio copys the object name (which is path + leaf name) as a single string and takes that to be the name of the object in rio. This makes pawgo break

```
paw> /hist/open h1 /file/id/f/MonoH_Truth/jets
paw: error: no record [MonoH_Truth] in file [id=f name=what.rio]
```

the best solution is to just use the same paths as in YODA and make them actual paths in rio I think

**Comment by lukasheinrich** [comment]
test file: https://gist.github.com/lukasheinrich/e80431626e7d7f48845199f8f6692a19

**Comment by sbinet** [comment]
(feel free to reopen if there's still an issue)
