### ISSUE TITLE
rootio: implement Create function to create new ROOT file

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#166]
```go
package rootio

func Create(fname string) (*File, error) { ... }
```

Get acquainted with `ROOT/C++`:

- [ ] inspect + understand:
   - [ ] [TFile::TFile](https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TFile.cxx#L221), with `options == "CREATE" || "RECREATE" || "NEW"`
   - [ ] [TFile::Open](https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TFile.cxx#L3949), with `options == "CREATE" || "RECREATE" || "NEW"`
- [ ] inspect + understand [TFile::Init(create=true)](https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TFile.cxx#L586)
- [ ] inspect + understand [TDirectoryFile::FillBuffer](https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TDirectoryFile.cxx#L725)
- [ ] inspect + understand [TFile::Close](https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TFile.cxx#L903)
- [ ] insepct + understand [TFile::WriteStreamerInfo](https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TFile.cxx#L3647)

once that's done:

- [ ] flesh out `func (f *File) writeHeader() error` (following [TFile::WriteHeader](https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TFile.cxx#L2491)
- [ ] implement `func (f *File) writeStreamerInfo() error` (following `TFile::WriteStreamerInfo`)
- [ ] improve `TestCreateEmptyFile` to create, close and then re-open empty file

## ROOT I/O main classes

- `TFile`:
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/inc/TFile.h
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TFile.cxx
- `TDirectoryFile`:
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/inc/TDirectoryFile.h
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TDirectoryFile.cxx
- `TKey`:
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/inc/TKey.h
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TKey.cxx
- `TBuffer`:
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/inc/TBufferFile.h
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TBufferFile.cxx
- `TStreamerInfo`:
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/inc/TStreamerInfo.h
   - https://github.com/root-project/root/blob/v6-12-00-patches/io/io/src/TStreamerInfo.cxx

**Comment by sbinet** [comment]
@maloft, I've slightly updated this issue with a few pointers to the guts of the main ROOT classes+methods.

**Comment by maloft** [comment]
[Making_of_a_new_ROOT_file.docx](https://github.com/go-hep/hep/files/2133558/Making_of_a_new_ROOT_file.docx)

**Comment by maloft** [comment]
@sbinet , 
[Closing_a_file.docx](https://github.com/go-hep/hep/files/2136017/Closing_a_file.docx)

**Comment by sbinet** [comment]
fixed by https://github.com/go-hep/hep/pull/338, https://github.com/go-hep/hep/pull/340
