### ISSUE TITLE
hbook/ntup: add example on how to create histos from CSV

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#186]
something like this usecase, for example:

- https://root-forum.cern.ch/t/how-to-read-a-dat-file-and-plot-as-histogram/28916

```go
nt, err := ntcsv.Open("testdata/simple.csv", ntcsv.Comma(' '), ntcsv.Comment('#'))
if err != nil {
    log.Fatal(err)
}
defer nt.DB().Close()

h := hbook.NewH2D(100, 0, 100, 50, 0, 50)
_, err = nt.ScanH2D("var1, var2", h)
```

**Comment by jaybatra26** [comment]
@sbinet . Can I take this one?

**Comment by sbinet** [comment]
SGTM. I am sure @sebgadrat won't mind :)

**Comment by sebgadrat** [comment]
@jaybatra26 Sure go ahead! :-)

**Comment by jaybatra26** [comment]
Thanks @sebgadrat 

One quick question, where would this example file go. Would it be a standalone go file or is there a specific folder where this kind of examples reside?

**Comment by sbinet** [comment]
usually, examples are put inside the directory holding the code for a given package.
we also try to use the Go way to create examples.

see:
- https://github.com/go-hep/hep/blob/master/hbook/h1d_test.go#L24

which then translates to:
- https://godoc.org/go-hep.org/x/hep/hbook#example-H1D

the nice thing with `ExampleXYZ` is that these examples are run as part of tests (with `go test`) as soon as they contain:
```go
// Output:
// something to test against.
```

so, in the case at hand, this would involve creating a new file, `ntup_example_test.go`, under `hep/hbook/ntup`:
```go
package ntup_test

func ExampleNtuple_scanH2D() {
    // ...
}
```

**Comment by sbinet** [comment]
> Would this be a part of ReadMe?

no, examples in Go are usually picked up from GoDoc.

> I see similar examples in test files. Can use the csv's in test for examples?

yep :)

**Comment by jaybatra26** [comment]
@sbinet Thanks a lot, This is really helpful. I have tried writing the example, but when I am trying to do `go build -o . ntup_example_test.go`. It says `no packages to build`. I would appreciate if you can help me understand why would this not work.

**Comment by sbinet** [comment]
examples are built and run with `go test`.
_e.g._:
```
$> cd go-hep.org/x/hep/hbook/ntup
$> go test -run=Example -v
```
the above should build and run all tests and examples functions which name start with `Example`.

see:
- https://blog.golang.org/examples
