### ISSUE TITLE
xrootd: consider renaming 'xrootd/protocol into 'xrootd/xrdproto'

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#212]
this would prevent the package name clash with `xrootd/protocol/protocol`.

this would also better mirror the naming convention in C++ `xrootd/XProtocol`.

ie:
- `"go-hep.org/x/hep/xrootd/xrdproto"`
- `"go-hep.org/x/hep/xrootd/xrdproto/protocol"`

what do you think @EgorMatirov ?

**Comment by EgorMatirov** [comment]
Looks good to me, since it sometimes ends up being `xrdproto` anyway. :)

**Comment by sbinet** [comment]
fixed by #216
