### ISSUE TITLE
fit: optimize.Local removed from gonum

### ISSUE THREAD

**Issue by SpencerPark** [go-hep/hep#290]
See https://github.com/gonum/gonum/pull/538

Getting `go/src/go-hep.org/x/hep/fit/curve1d.go:28:9: undefined: optimize.Local` when running `go get -insecure go-hep.org/x/hep/fit` (in the gophernotes `Dockerfile.DS`).

**Comment by SpencerPark** [comment]
Can confirm all builds fine now, thanks!

**Comment by sbinet** [comment]
and thanks for the report! :)
