### ISSUE TITLE
rootio: enable fileplugin test on Windows

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#334]
when enabling AppVeyor for Windows, an interesting behaviour difference wrt Linux showed up for `TestTmpFile` (in fileplugin_test.go):

- https://ci.appveyor.com/project/sbinet/hep/build/1.0.16
```
--- FAIL: TestTmpFile (0.00s)
	fileplugin_test.go:48: file "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rootio-remote-371892235" should have been removed
FAIL
```

ie:
- https://github.com/go-hep/hep/blob/304b3b83f0a3d78b1a99349e9fef7f6bb1bec78d/rootio/fileplugin_test.go#L48
- https://github.com/go-hep/hep/blob/304b3b83f0a3d78b1a99349e9fef7f6bb1bec78d/rootio/fileplugin.go#L58

it would seem removing the file as part of calling `tmpFile.Close` doesn't work the same on Windows as it does on Linux.

**Comment by EgorMatirov** [comment]
When I change `Close` to:
```go
func (f *tmpFile) Close() error {
	err := os.Remove(f.File.Name())
	if err != nil {
		log.Panic(err)
	}
	return f.File.Close()
}
```
it panics with
```
remove C:\Users\ematirov\AppData\Local\Temp\rootio-remote-461405571: The process cannot access the file because it is being used by another process.
```

Looks like we cannot close currently opened file (that makes some sense).
