### ISSUE TITLE
rootio: add all dependant streamers when writing

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#370]
right now, `rootio` checks that it knows about a given type's streamer, when one does:
```go
f, err := rootio.Create("out.root")
f.Put("my-key", value)
```

the streamer for `value` is added to the output file.

but if, e.g., value is of type `rootio.H1D`, `rootio` will only add the streamer for `TH1D`.
it's missing the whole hierarchy of streamers (`TH1`, `TNamed`, `TAttLine`, `TAttFill`, ...) as well as the streamers for the fields of `TH1D` (`TArrayD`, `TArray`, ...)

**Comment by sbinet** [comment]
it was the quickest way to get forward and make sure the ROOT streamers definition b/w ROOT/C++ and `rootio` would match.

for user-types' streamers, the plan is to have:
- the streamer automatically generated at runtime (using `reflect`)
- the streamer automatically generated by a program (using `go/types`, something like go-hep.org/x/hep/brio/cmd/brio-gen does) to not incur too much reflection performance hit.

most of the code for automatically generating a streamer is actually there in some form: that's how a user can give a `type MyEvent struct { ... }` to the `rootio.TreeScanner` and read data back in.

but yes, for ROOT/C++ classes, I think it's easier and more robust to have the streamers generated by ROOT itself and use that directly.
the plan is to break this huge `rstreamers` package into multiple ones (say one for the `rhist` package, one for `rtree`, one for `roofit`, ...) that can be blank-imported.

**Comment by decibelcooper** [comment]
Thanks!  The best I can do right now AFA contributing is to try to keep up with your developments, and look for the opportunity to help with code.
