### ISSUE TITLE
xrootd: consider merging xrootd/client and xrootd/server

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#408]
currently, 

- creating an XRootD client is done like so:
```go
import "go-hep.org/x/hep/xrootd/client"

func F() {
    cli, err := client.NewClient(ctx, addr, usrname)
}
```

- creating an XRootD server is done like so:
```go
import "go-hep.org/x/hep/xrootd/server"

func F() {
    srv := server.New(handler, errHandler)
}
```

if we were to merge both `xrootd/client` and `xrootd/server` into, just, `xrootd`, this would:
- reduce package stutter:
```go
import "go-hep.org/x/hep/xrootd"

func F() {
    cli, err := xrootd.NewClient(...)
    srv := xrootd.NewServer(...)
}
```

- reduce the amount of boilerplate code for testing the `C++`, `Go` servers and clients.

@EgorMatirov what do you think?

**Comment by EgorMatirov** [comment]
@sbinet sounds reasonable. Looks like we don't have much overlapping names, so it would not be a problem.

Also, `xrootd` package name looks more user-friendly that just a `client` or `server`.

**Comment by sbinet** [comment]
ok. doing it now...
