### ISSUE TITLE
rootio: support for TGraph

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#49]
@aphecetche wants them

**Comment by mughetto** [comment]
Interested as well, do you already have plans on how to solve this issue? Looks like it could simply be a special way of plotting a scatter plot (special in the sense that ordering becomes apparent)

**Comment by sbinet** [comment]
the first step is to be able to read `TGraph` (and possibly `TGraphError` too) from a `TFile`.
so this means creating the equivalent of a `ROOT` streamer for `x/hep/rootio`.

then, one would need to add support for converting these `TGraph` to the `YODA` file format so these can be (converted to `x/hep/hbook.Scatter2D` and then) plotted with `root-srv` (or rootio-inspector.appspot.com).

let me whether I can tackle the first step :)

**Comment by sbinet** [comment]
@mughetto could you give the `tgraph-support` branch a spin?

it only implements the first step (reading `TGraph{Errors}` from a `TFile`.
and no tests (yet!)
creating a `hbook.Scatter2D` should be easy (w/o having to go through the `YODA` dance, actually)

**Comment by mughetto** [comment]
Indeed the creation of a hbook.Scatter2D is pretty straightforward using the hbook.NewS2DFrom( ) constructor. Made some plots and they looks as expected. I guess next step is to provide a patch to add a constructor with errors provided as arrays.

**Comment by sbinet** [comment]
ok, good!

I merged a slightly different version of the `rootio.Graph{,Errors}` API.
mainly to implicitly implement the `gonum/plot/plotter.XYer`, `XErrorer` and `YErrorer` interfaces.
(so `rootio.Graph` and `rootio.GraphErrors` can be plotted directly with `gonum/plot`)
