### ISSUE TITLE
feature request on hplot

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#612]
I would like to propose two features, which - I think - would be very valuable to do data analysis in high energy physics:
 - [x] ~~histogram style with points only (no line, no rectangles), since this is the way we represent observed data in HEP~~ (fixed w/ go-hep/hep#615)
 - [ ] enable stack histogram to show various sources of contribution, which is also standard in HEP.

As an example of how usual HEP plot look like ([arXiv:1206.2967](https://arxiv.org/pdf/1206.2967.pdf)):
![image](https://user-images.githubusercontent.com/30081646/78560013-a2407100-7815-11ea-9f2a-bcd1d5460144.png)

**Comment by sbinet** [comment]
see https://github.com/go-hep/hep/pull/617

**Comment by rmadar** [comment]
You rock!
