### ISSUE TITLE
Questions / issues on hplot cosmetics

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#613]
I was trying to perform few plot cosmetics and I had some trouble to do the following things. I am not sure if the features are missing or if I wasn't able to find them. Also, I think some of them propagate to the `gonum/plot` package, on which `hplot` is built on.

 1. How to change histogram markers style/size? I saw how to do do it with S2D, but `h.Shape = draw.CircleGlyph{}` doesn't work.

 2. How to draw an histogram with v.s. without line (like only point such as - conventionally - for observed data histogram in HEP)?
 
 3. How to change the position axis labels? I tried the comand `p.X.Label.XAlign = draw.XRight` but it didn't send the label to the right for instance (even if it moves a bit), as shown below:

*before the command*
![image](https://user-images.githubusercontent.com/30081646/78560660-b46edf00-7816-11ea-8015-490313e72aae.png)

*after the command*
![image](https://user-images.githubusercontent.com/30081646/78560731-cfd9ea00-7816-11ea-816d-d6cac5ce7da5.png)

 4. How to change canvas padding to avoid the plot to end where the PDF file ends?
![image](https://user-images.githubusercontent.com/30081646/78560858-06176980-7817-11ea-8cd0-7c7feaa11f1d.png)

**Comment by sbinet** [comment]
for 1) and 2), see #615 

for 3), this will probably have to be addressed at `gonum/plot`'s level (let me check).

for 4): is this only present with the PDF backend or do you see that also with, say, the PNG one?

**Comment by rmadar** [comment]
> for 4): is this only present with the PDF backend or do you see that also with, say, the PNG one?

I also see it with PNG backend:
![image](https://user-images.githubusercontent.com/30081646/78569509-066a3180-7824-11ea-8953-49f041c8826a.png)

which also doesn't handle very well transparency, since the above plot in PDF looks like this:
![image](https://user-images.githubusercontent.com/30081646/78569731-50531780-7824-11ea-916e-3b5e80b18d16.png)

**Comment by sbinet** [comment]
see https://github.com/gonum/plot/issues/589 for `3)`.

**Comment by sbinet** [comment]
for the transparency handling in the PNG backend, I suspect one needs to use `image.NRGBA` (instead of `image.RGBA`)

**Comment by rmadar** [comment]
Ok. I probably didn't do [things properly for PNG](https://github.com/rmadar/go-simple-examples/blob/master/plotting/main.go#L125) then, because I didn't even call `image.RGBA` :)

**Comment by sbinet** [comment]
sorry, I meant `color.NRGBA` instead of `color.RGBA`.

**Comment by sbinet** [comment]
as for `4)`, do you want to be able to specify different border sizes top/bottom/left/right or one single border size?

**Comment by rmadar** [comment]
I would say that a single padding for the four sides will do it. But if its not too much work to add four, it might save time for the next time... It doesnt help so much, right ;-) ?

**Comment by sbinet** [comment]
done: https://github.com/go-hep/hep/pull/616

**Comment by rmadar** [comment]
I am not sure I can try unmerged PR so maybe ignore my last comment on #614 (even if the opacity worked ... Well, I am not sure which version I tried). 

---

In any case, I tried the 'dots-like' histogram feature with
```go
hplot.WithGlyphStyle(draw.GlyphStyle{
	Shape:  draw.CrossGlyph{},
	Color:  color.Black,
	Radius: vg.Points(2)}),
```
And it looks quite good! There is just one small missing part: the marker doesn't appear in the legend:

![image](https://user-images.githubusercontent.com/30081646/78603610-b3f73800-7858-11ea-8ed9-d7891bdf5bdc.png)

Also, trying to put the line back, the legend consider it as a filled histo without color, not a line:

![image](https://user-images.githubusercontent.com/30081646/78603744-f0c32f00-7858-11ea-91dd-04d901b62973.png)

**Comment by sbinet** [comment]
yeah, trying out not-yet-merged-in PRs is a bit painful (you'd have to clone `gonum/plot`, cherry-pick "my" changes, and `go.mod replace` `gonum/plot` to point at the local clone).

thanks for trying it out and kicking the "legend" tyres.
I'll have a look tomorrow. (and perhaps steal your plot and promote it as an example)

**Comment by rmadar** [comment]
OK #616 works well. The only thing is that it doesn't propagate to LaTex format. Since this option was done at the `hplot` level, and since the LateX conversion is handled at the `gonum/plot` level. That might be difficult to handle, I guess?

---

**PDF output without LaTeX**

![image](https://user-images.githubusercontent.com/30081646/78669809-1db92580-78dd-11ea-87a4-8f240456bbad.png)

**PDF output with LaTeX**

![image](https://user-images.githubusercontent.com/30081646/78669775-12fe9080-78dd-11ea-88c0-c481d5808a7d.png)

**Comment by sbinet** [comment]
it seems it could be a bit convoluted, indeed.

I've filed https://github.com/gonum/plot/issues/597 to not forget about this.

in the meantime:
- https://github.com/go-hep/hep/pull/622

**Comment by sbinet** [comment]
I believe all issues have been addressed.

feel free to reopen otherwise.

**Comment by rmadar** [comment]
Thanks a lot! Borders now works with pdflatex and the black point is added to the legend. But I would still have two follow-ups (I don't know how to re-open an issue):
 
  1. the border with the following syntax doesn't seems to work well
```go
c := vgimg.NewWith(
      vgimg.UseWH(12*vg.Centimeter, 9*vg.Centimeter),
      vgimg.UseDPI(200)
)         
dc := draw.New(c)
p.Draw(dc)
saveImg(c, "results/h1d_plot.png")
``` 
 2. I think the data point in the legend would look better with the error bar on it (like 3 times the point radius or something like this). I have no idea if this is tricky or easy to do.

**Comment by sbinet** [comment]
`1)` should be addressed by https://github.com/go-hep/hep/pull/624

I'll see what I can do for `2)`.

**Comment by rmadar** [comment]
It works like a charm! Thanks !!

![image](https://user-images.githubusercontent.com/30081646/78768017-a2627d00-798b-11ea-855c-a9d96ef193ec.png)

**Comment by rmadar** [comment]
For 3), I have tested `Axis.Label.Position` field, and it works well ... except in LaTeX - due to the same issue mentioned in #618 about string length assessment, I guess :

![image](https://user-images.githubusercontent.com/30081646/79044175-fa0b1d80-7c03-11ea-8029-31d125a8a6b5.png)

**Comment by sbinet** [comment]
yep.
(working on the (limited) LaTeX parser as we speak...)

**Comment by rmadar** [comment]
That's great because my little hack mentioned [here](https://github.com/go-hep/hep/issues/618#issuecomment-611965497) actually doesn't work: the additional `\vspace{}` put by hand depends (obviously) of the total length of all LaTeX commands in the string, which you don't know - unless you don't have parser ;-)

![image](https://user-images.githubusercontent.com/30081646/79044640-80c0fa00-7c06-11ea-8ba3-e5b8363ca363.png)
