### ISSUE TITLE
Issues with LaTeX output of hplot

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#614]
I was trying the LaTeX output that `hplot` provides and I noticed two issues:

 1. transparency crashes during LaTeX compilation:
the command `norm.Color = color.RGBA{R: 255, A: 100}` generate the latex compilation: `! Package color Error: Argument '2.55' not in range [0,1].`

 2. change of fontsize via `p.Title.TextStyle.Font.Size = 25` doesn't propagate to pdf generated by LaTeX

 3. more a suggestion: is there a way to skip the `pdflatex plot.tex` step while using `hplot` and have the output directly in PDF?

**Comment by sbinet** [comment]
I'll handle `1)` and `2)` in `gonum/plot` directly.

let me think a bit about APIs for `3)`.

**Comment by sbinet** [comment]
- [ ] gonum/plot#592 (font size)
- [ ] gonum/plot#593 (opacity/alpha-channel)

**Comment by sbinet** [comment]
could you try again, now the PRs have been merged?
(_"it works for me"_ (TM))

**Comment by rmadar** [comment]
I was about to reply ... but wanted to beautiful the output a bit and (I am not done yet). But it starts to look nice. I might open a couple of other issues related to small cosmetic details - but it starts to be details ;-) !

![image](https://user-images.githubusercontent.com/30081646/78667556-7686bf00-78d9-11ea-8205-438045c64b51.png)

**Comment by sbinet** [comment]
cool!

fixed w/ gonum/plot#592 & gonum/plot#593.

**Comment by sbinet** [comment]
(oops, forgot about `3)`...)

**Comment by sbinet** [comment]
see https://github.com/go-hep/hep/pull/623

**Comment by rmadar** [comment]
Thanks a lot for this (It is much more convenient now) !

But I would like to make a comment concerning LaTeX handling, which is probably much more general and involve deeper modifications. So don't want to re-open the issue, but just follow up on it. And I would be happy to hear your opinion on it (and how difficult would be the changes).

In other plotting tool, like `ROOT` or `matplotlib`, the use of LaTeX is completely (or almost completely) transparent for the user. I mean that I don't have to choose in advance if I want to use LaTeX or not when writing the labels, or selecting the final file format.

Right now, I am facing these two concretes situations:
 1. I have two kinds of labels (for axis, title etc ...), one with LaTeX and one without. This makes rather uneasy the switch from one format to another, or simply the optimization of how the plot appearance.
 2. can I get a `png` file with math symbol in it (I mean without `pdf-to-png` by-hand conversion), such as:
![image](https://user-images.githubusercontent.com/30081646/78721908-b1fcaa00-7928-11ea-9c49-68cb320dd942.png)
