### ISSUE TITLE
Minor issues with the legend (and possibly Latex conversion)

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#618]
Playing with the legend, I realized that 
 1. related to `gonum/plot` (I guess): the text is not vertically centered with respect to the symbol of the plot
 2. related to `hplot` (I guess): the histogram filling mode is a cut on the left (increasing `p.Legend.ThumbnailWidth` doesn't solve it)

![image](https://user-images.githubusercontent.com/30081646/78676350-9c669080-78e6-11ea-96e1-2972777314c8.png)

However, for `2.`, I think it might be connected to another issue I have noticed with LaTeX conversion: the histogram fill without line still show a kind of line (see above) which is not present in the native PDF exportation (w/o LaTeX):

![image](https://user-images.githubusercontent.com/30081646/78676819-4219ff80-78e7-11ea-8371-319c40cc0ab3.png)

**Comment by rmadar** [comment]
About `2.`, I realized that if you have a first legend entry before the filled-only histo, then it works (if it helps debugging):
![image](https://user-images.githubusercontent.com/30081646/78680102-5d870980-78eb-11ea-867e-2b0f152740e8.png)

**Comment by rmadar** [comment]
I would like to add something else I have noticed (not sure if this is mis-use on my side or an issue). The text alignment with respect to the thumbnails in the legend seems different if we use math environment of not:

![image](https://user-images.githubusercontent.com/30081646/78798622-7fe75880-79b9-11ea-9a78-3144f1aac7df.png)

**Comment by rmadar** [comment]
I would like to raise another cosmetic point about the legend thumbnails for 'dots' and/or 'line' style. Currently, it looks like this:

![image](https://user-images.githubusercontent.com/30081646/78892326-7b7a7880-7a69-11ea-9d19-7fbdf225998d.png)

I think it would look better if the box would be replaced by a straight line (as for functions). This would work better for all configuration, I think:
  + line and not filled: just a line
  + line and filled: a colored box (w/o border) + a line in the middle
  + line w/ circle: line+circle in the middle
  + line w/ circle w/ fill: colored box with a line in the middle, plus a dot in the middle of the line

**Comment by sbinet** [comment]
wrt your comment in https://github.com/go-hep/hep/issues/618#issuecomment-611006611

> I would like to add something else I have noticed (not sure if this is mis-use on my side or an issue). The text alignment with respect to the thumbnails in the legend seems different if we use math environment of not:

it's coming from the same issue than in https://github.com/go-hep/hep/pull/626 where the strings that are written on canvas are measured before they are "processed".
ie: they are measured with all the characters that make _e.g._ `"$t\bar{t}$ full ME"` (and "aligned" with that length in mind) while the LaTeX will just draw ``tt full ME"`.

see for a legend w/ + w/o math expressions:
![out](https://user-images.githubusercontent.com/1070920/78973042-550f1880-7b0f-11ea-93e4-2ca538b36420.png)

I am afraid fixing this will take some time (_ie:_ implementing that math expression parser from #628 )

**Comment by rmadar** [comment]
OK, I see. Thanks for the explanation. I might a temporary fix, but not sure it's clean enough to be implemented in a standard tool. We call this function only for latex format (if possible?):

```go
// Helper to manage LaTeX legend label
func alignLaTexLegendLabel(legLeft bool, legFontSize int, legLabel string) string {
        if legLeft {
                return fmt.Sprintf(`\hspace{-%vcm}`, 4*legFontSize/12) + legLabel 
        } else {  
                 return legLabel + fmt.Sprintf(`\hspace{-%vcm}`, 4*legFontSize/12) 
        } 
} 
```

I tried for different fontsize, thumbnail size and canvas size: it seems OK. The only thing is that latex compilation fails is the size passed to `p.Save(5*vg.Inch, 5*vg.Inch`) is smaller than the `hspace` Note that `legFontSize` should be `vg.Length` in principle (not a integer) and should be ten converted into centimeters somehow.

This is the result on few examples:

![image](https://user-images.githubusercontent.com/30081646/78977135-e4b8c500-7b17-11ea-941d-3094c74bb42c.png)

![image](https://user-images.githubusercontent.com/30081646/78977187-fe5a0c80-7b17-11ea-9505-33517dc6c086.png)

![image](https://user-images.githubusercontent.com/30081646/78977218-0fa31900-7b18-11ea-9d37-907c38936419.png)

![image](https://user-images.githubusercontent.com/30081646/78977316-35c8b900-7b18-11ea-8d6a-a4c2fa2226b8.png)

![image](https://user-images.githubusercontent.com/30081646/78977375-5133c400-7b18-11ea-8445-9ec0ce74ab33.png)

![image](https://user-images.githubusercontent.com/30081646/78977864-272ed180-7b19-11ea-95cd-b9e162f53131.png)

**Comment by rmadar** [comment]
Update with a check whether there are equations or not, and apply a different alignment. This is totally a hack but this work for a fontsize in [9, 25]. I'll have to try with other font ...

```go
// Helper to manage legend label                                                     
func alignLegendLabel(legLeft bool, legFontSize vg.Length, legLabel string) string { 
                                                                                     
        if strings.Count(legLabel, `$`) == 0 {                                       
                offset := - 2.8 * float32(legFontSize) / 12.0                        
                if legLeft {                                                         
                        return fmt.Sprintf(`\hspace{%.1fcm}`, offset) + legLabel     
                } else {                                                             
                        return legLabel + fmt.Sprintf(`\hspace{%.1fcm}`, offset)     
                }                                                                    
        } else {                                                                     
                offset := - 4.18 * float32(legFontSize) / 12.0                       
                if legLeft {                                                         
                        return fmt.Sprintf(`\hspace{%.1fcm}`, offset) + legLabel     
                } else {                                                             
                        return legLabel + fmt.Sprintf(`\hspace{%.1fcm}`, offset)     
                }                                                                    
        }                                                                            
```

The result with equation and not equation text:

![image](https://user-images.githubusercontent.com/30081646/78982282-16368e00-7b22-11ea-96b1-65f1f95494d0.png)

**Comment by sbinet** [comment]
I am trying to debug the weird "half open" rectangle for the gray histo legend (running your `analyzer-show` rmadar/tree-gonalyzer@ed84105.

it seems it's when converting this pdf file:
[truth_dphi_ll.pdf](https://github.com/go-hep/hep/files/4461048/truth_dphi_ll.pdf)

to a png one (using `convert foo.pdf foo.png`):
![out](https://user-images.githubusercontent.com/1070920/78983152-ef795700-7b23-11ea-8dfb-144bb92776ba.png)

that I get this behaviour.
(not sure why).

do you confirm?

but all I get is:

**Comment by rmadar** [comment]
I don't convert things in `png` (for issues, I am just just doing screenshot of my `pdf` viewer). So I confirm that I have the issue with the `pdf` file. I tried two different viewer (`okular` and `evince`) and they lead to the same behavior). 

![image](https://user-images.githubusercontent.com/30081646/78988019-0625ab00-7b30-11ea-9281-7e994fe33820.png)


But I tried with the viewer on my phone and there, it was OK. Do you manage to at least reproduce the problem with `evince` or `okular`?

**Comment by sbinet** [comment]
do you see this with the pdf file I've uploaded here:
https://github.com/go-hep/hep/files/4461048/truth_dphi_ll.pdf
?

(could you add one of your PDF files where you see the issue?)

**Comment by sbinet** [comment]
nevermind.

found it.

**Comment by rmadar** [comment]
Yes, I checked and I saw the opened rectangle. All the `pdf` in [tree-gonalyzer/analyzer-show/results](https://github.com/rmadar/tree-gonalyzer/blob/master/analyzer-show/results) have the issue for me

**Comment by rmadar** [comment]
> do you see this with the pdf file I've uploaded here: https://github.com/go-hep/hep/files/4461048/truth_dphi_ll.pdf ?

Actually, no: I don't see it (before I checked on my phone only, now I think about it)! I still see a "double line" but that's probably something else, one step at a time!

![image](https://user-images.githubusercontent.com/30081646/78989717-aaa9ec00-7b34-11ea-900d-eae5de9799d6.png)

**Comment by sbinet** [comment]
I believe all issues (except for LaTeX-legend-horizontal offset one) have been either fixed in `hplot` or have a fix submitted to `gonum/plot`:

- half-open rectangle: go-hep/hep#633
- change thumbnail of H1D to have "skyline" of histo as a horizontal line at mid-height of thumbnail: go-hep/hep#633
- extra line in histo-fill and thumbnail: gonum/plot#602

**Comment by rmadar** [comment]
That's perfect (I'll follow gonum/plot issues)! Thanks
