### ISSUE TITLE
Minor improvements on Y error bars style

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#619]
I have notices a couple of minor issues for the Y error bars style, which after being fixed, could improve the quality of plots.

1. Changing the LineStyle of the background grid affect the appearance of the error bar style and the function line too **only with `pdflatex`**. Left: grid with dashed-lines. Right: grid without changing line style (wrt `hplot.NewGrid()`).
![image](https://user-images.githubusercontent.com/30081646/78678051-be611280-78e8-11ea-9f66-8e41b7fa381b.png)

2. A change of `h.YErrs.LineStyle.Width = 1` doesn't seem to scale to all elements of the error bar (length of the small vertical tick, for instance), which ends in loosing its shape. Left (Right) width of 5 (1). 

![image](https://user-images.githubusercontent.com/30081646/78678987-f3219980-78e9-11ea-96dd-e0a80430b22a.png)

3. Transparency doesn't have the expected behavior for the error bar (left: native PDF, right: LaTeX). I understand this might implies tricky modification, probably create a marker with error bar as a whole single object. And I know this is being picky, so feel free to ignore/postpone this one!

![image](https://user-images.githubusercontent.com/30081646/78679590-b7d39a80-78ea-11ea-8be9-13df9021d01a.png)

**Comment by sbinet** [comment]
for `2)`, (I think) you need to also modify the `CapWidth` field of `plotter.YErrorBars`:
https://godoc.org/gonum.org/v1/plot/plotter#YErrorBars

**Comment by sbinet** [comment]
for `1)`, https://github.com/gonum/plot/pull/599 should fix it.

(what about `2)`? was my assumption correct?)

**Comment by rmadar** [comment]
Yes it was! I'll try the fix for the line style!

**Comment by sbinet** [comment]
tentatively closing as gonum/plot#599 has been merged. (feel free to reopen if that didn't fix it)

`3)` is probably something to live with for the time being, I am afraid. (feel free to file that part against the [gonum/plot](https://github.com/gonum/plot/issues/new) repo directly.)

**Comment by rmadar** [comment]
Yes, it is fixed (I just tried). For `3)`, I agree - no pb! Thanks
