### ISSUE TITLE
fastjet: implement EeKtAlgorithm

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#63]
now that EeGenKtAlgorithm is in, we should also implement the e+e- kt algorithm to be on par with the set of features of the `C++` version of FastJet.

@Bastiantheone do you want to give it a try? :)

**Comment by Bastiantheone** [comment]
Yes I can do that

**Comment by Bastiantheone** [comment]
@sbinet can you provide me with testdata files for this algorithm?

**Comment by sbinet** [comment]
yep. will do as soon as I am in front of a real keyboard :)

**Comment by sbinet** [comment]
@Bastiantheone see be0fad3.
Note that, for e+e- kt, the original test from `C++` FastJet runs with exclusive jets. so this mode would need to be implemented first. (I've created go-hep/hep#65 to track that)
