### ISSUE TITLE
Possible to use NewReader(tree, &data) syntax?

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#637]
Playing with `rtree.NewScanner` and `rtree.NewReader`, I experienced that the following code works:
```go
var data Data
sc, err := rtree.NewScanner(tree, &data) 
```
while the equivalent with `NewReader` is not implemented (unless I used it wrongly):
```go
var data Data
r, err := rtree.NewReader(tree, &data) 
```

Even if not absolutely necessary, I think this syntax is quite nice and I would personally use it, if available in `rtree.NewReader`.

**Comment by sbinet** [comment]
one possible way would be to write a function not unlike [rtree.WriteVarsFromStruct](https://godoc.org/go-hep.org/x/hep/groot/rtree#WriteVarsFromStruct), which could then be used like so:

```go
var data Data
r, err := rtree.NewReader(tree, rtree.ReadVarsFromStruct(&data))
```

what do you think?

**Comment by rmadar** [comment]
Yes I think that would be nice (also in the way that is would be symmetric for writing and reading), thanks!
