### ISSUE TITLE
rootio/cmd/root-srv: implement https+letsencrypt

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#64]
add support for https (and thus, HTTP/2) with Let's Encrypt.

**Comment by sbinet** [comment]
@mughetto, do you want to give that a spin?

**Comment by sbinet** [comment]
(it's relatively easy, see:

**Comment by sbinet** [comment]
and it could even be easier with the new `NewListener` feature:
https://godoc.org/golang.org/x/crypto/acme/autocert#example-NewListener

**Comment by mughetto** [comment]
Having a look at the moment

**Comment by mughetto** [comment]
Got a nearly working version, just got to figure out how to configure a certificate on localhost.

Do you want to support both http and https or systematically redirect http connections to https?

**Comment by mughetto** [comment]
Any idea how I could test witout having a public domain name certbot could use?

**Comment by mughetto** [comment]
Got a working test version, just want to implement a proper http->https redirection in case the server runs https before making the PR

**Comment by sbinet** [comment]
(sorry for the belated answer)

here is an example of this http->https redirection:
https://github.com/go-hep/go-hep.org/blob/master/main.go#L51

(but you can already send your PR, and we'll iterate)
