### ISSUE TITLE
groot/rtree: modify Formula to take a receiver ptr

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#647]
as per https://github.com/go-hep/hep/pull/646#issuecomment-615065217:

---
another option would be to require the user to provide a `*T` where to store the return value:

```go
r, err := rtree.NewReader(...)

// access result via 'v1' or form1.Eval().(float64)
var v1 float64
form1, err := r.Formula(&v1, "br1+br2", nil)

// access result via 'v2' or form2.Eval().(bool)
var v2 bool
form2, err := r.Formula(&v2, "br1 > 42", nil)

// infer type from expression.
// access result via form3.Eval().(float64)
form3, err := r.Formula(nil, "br1+br3", nil)
```

this removes another `reflect` call per event iteration.

**Comment by sbinet** [comment]
after playing with this idea in https://github.com/go-hep/hep/pull/690 (as part of deriving benchmark figures), I am not sure this is a good idea anymore:

API-wise, it relies on some side effect:
```
// decl
var v1 float64
f1, err := r.Formula(&v1, "br1+br2", nil)

// during evt-loop
f1.Eval()      // side-effect: "magically" fills v1
if v1 > cut1 { // silently breaks if one forgets to call f1.Eval
    // ....
}
```
this could be fixed by calling the `Eval()` method of all known attached formulae.
... even those that may not be needed
... even those that may not be needed _and_ take a fair amount of CPU.
this makes performances of a program less predictible.

so I'd be tempted to leave the current API as-is.
(the last batch of perf-improvements shaved another set of allocations and cpu-cycles anyways)

**Comment by rmadar** [comment]
OK, indeed these caveats are in ROOT - and it's not a very nice behavior.

Thinking more about it, I was wondering if it would be possible to have another approach (possibly on top of the existing one). This is mostly to brainstorm and not necessarily to try now. Couldn't we use the interpreter to *only* get the branch values, and directly give a go function for the mathematical operation - then really compiled (and then fast)?

Let's assume we have this formula:
```go
f1 := r.Formula("math.Sqrt(pT1+pT2)", "math")
```
We could think of declaring the same information in the following way:
```go
// New type
type varExpr struct {
   bnames []string
   f func ([]float64) float64
}

myObs := varExpr{
    bnames: []string{"pT1", "pT2"},
    f: func(xs []float64) {return math.Sqrt(x[0]+x[1])}
}

f2 := r.NewFormulaFromExpr(myObs)
```

The syntax is a bit heavier (although I am sure we can improve it) but the main feature is kept: not having to explicitly load needed branches. If such an approach is possible (and assuming it brings perfs close to `rtree.ReadVar` ones), I would still keep both ways, depending on the use case.

**Comment by sbinet** [comment]
thanks!
here is what it could look like: https://github.com/go-hep/hep/pull/691

**Comment by rmadar** [comment]
Nice (that was fast!!)! So it seems we can get another 15-30% improvement, meaning roughly twice slower than the direct access via `rtree.ReadVar`. 

There is something I don't understand though: now, there is no more "interpreted" operation, right? So why don't we get the same time than the `rtreeReadVar`? If you just load branches, and call a go function on it, it should be the same as ... loading branches and calling a go function on the values :) (I guess I am missing something but ...)

Anyway, it is definitely cool !
