### ISSUE TITLE
hep/sliceop/f64s: new package for operations on []float64

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#650]
`gonum/floats.Filter` was rejected in https://github.com/gonum/gonum/issues/1310.

perhaps we could consider adding it to a new `f64s` package (tentative name):

```go
package f64s

func Filter(dst, src []float64, f func(v float64) bool) []float64 {}
func Map(dst, src []float64, f func(v float64) float64) []float64 {}
func Find(dst []int, src []float64, f func(v float64) bool) []int {}
```

ex:
```go
o := f64s.Filter(nil, src, fct)
o := f64s.Filter(make([]float64, len(src)), src, fct)

o := f64s.Map(nil, src, func(v float64) float64 { return v*2 })
o := f64s.Map(make([]float64, len(src)), src, func(v float64) float64 { return v*2 })
```

@rmadar, do you want to take a stab at it?

**Comment by rmadar** [comment]
Yes, I am happy to implement this new package. I'll just need some instruction on how to proceed git-wise to add the corresponding file and ask for a merge request.

**Comment by sbinet** [comment]
you'll need to "fork" `go-hep/hep` into your `rmadar` namespace (just click on the `"Fork"` button of this page, upper right corner).

then:
```
$> cd somewhere
$> git clone git@github.com:rmadar/hep && cd hep
$> git remote add upstream git@github.com:go-hep/hep
$> git fetch --all -p
$> git checkout -b issue-650 upstream/master
$> mkdir -p ./sliceop/f64s
$> touch ./sliceop/f64s/f64s.go
```

also, please read the [/contribute](https://go-hep.org/contributing/#code-contribution) document.

**Comment by rmadar** [comment]
OK perfect, I did a first commit with the three functions. For the push, I am asked the following:
```
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push upstream HEAD:master

To push to the branch of the same name on the remote, use

    git push upstream issue-650
```

What is recommended when doing such developments?

**Comment by sbinet** [comment]
you need to push to your fork's branch:

```
$> git push origin issue-650
```

this will then propose to send a pull request.
(yeah, github is a bit cumbersome with insisting to fork a repo to be able to send PR against it...)

**Comment by sbinet** [comment]
https://godoc.org/go-hep.org/x/hep/sliceop/f64s

**Comment by rmadar** [comment]
very cool!
