### ISSUE TITLE
hbook: Add() and Divide() function for histograms

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#652]
While plotting ratio of two histograms, where one is a sum of many component, having functions like
```go
htot := hbook.AddH1D(h1, h2, m)    // doing h1 + m*h2 bin-by-bin
hratio := hbook.DivideH1D(h1, h2)  // doing h1/h2 bin-by-bin
```
would be quite useful (it could also be function of `hbook.H1D` directly). These functions also needs to correctly propagate uncertainty from both `h1` and `h2`, to the result. And I didn't find the analog of `h.Value(i)` function for error, same for `h.Fill(x, val)` (I might have missed it though).

I am happy to help and provide an approximate version of such function (once I know how to get/set H1D uncertainties).

**Comment by sbinet** [comment]
looking at `hbook.H1D.Value` (historically, implemented so hbook.H1D would implement gonum/plot/plotter.XYer`):
https://github.com/go-hep/hep/blob/master/hbook/h1d.go#L246
```
return h.Binning.Bins[i].SumW()
```

which is calling `hook.Bin1D.SumW()`.

looking at `Bin1D`, we see:
https://github.com/go-hep/hep/blob/420d16dfb83ee26b7e6762f3b3c647248676ea96/hbook/bin1d.go#L37

and a couple of lines below:
https://github.com/go-hep/hep/blob/420d16dfb83ee26b7e6762f3b3c647248676ea96/hbook/bin1d.go#L47
https://godoc.org/go-hep.org/x/hep/hbook#Bin1D.ErrW

(`hbook` is just a transliteration of [YODA](https://yoda.hepforge.org/) into Go, with a pun on the old `HBOOK` library in `FORTRAN`)

in terms of API, I'd go with:
```go
package hbook

func AddH1D(h1, h2 *H1D) *H1D {...}
func AddScaledH1D(h1 *H1D, alpha float64, h2 *H1D) *H1D {...}
func ScaleH1D(a float64, h *H1D) *H1D {...}
func DivH1D(h1, h2 *H1D) *H1D {...}
```

**Comment by rmadar** [comment]
OK I started to implementation the first function in https://github.com/go-hep/hep/pull/655

**Comment by rmadar** [comment]
All functions (but `ScaleH1D` which already exists as a method it seems) are implemented. I set NaN values to 0 in the `DivH1D()` function, but let me know if you think other convention/procedure should be used.

**Comment by sbinet** [comment]
I think it's fine (unless ROOT and/or YODA do this differently?)
