### ISSUE TITLE
Proposition to add a plotting style for hplot.S2D

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#669]
Trying to play a bit with ratio plots and histogram ratio as `S2D`, I was wondering if it would be possible to add a histogram-like plotting style fo `S2D`. Indeed, as you can see on 

![image](https://user-images.githubusercontent.com/30081646/79964771-77981e80-848b-11ea-8746-bd970f3b43d5.png)

the ratio plot is not done "per bin" while this would be more suggestive from the visual point of view (and this is also how histogram ration are usually displayed). In practice: one line as a histogram and the band around it.

Thinking about it, I would see two possible options:
 1. have a function `func NewH1D(s S2D)` but the returned `H1D` wouldn't have the right statistical attributes, *and* we would loose the super nice band feature (which I think should be added to histo for uncertainty plotting actually - but this could be discussed in another issue).
 2. have a new functional option like `hplot.NewS2D(s, DrawLikeHist(true))` (we can think of a better name) which would artificially plot only horizontal lines (connecting `(x[i]-xerr[i], y[i])` and `x[i]+xerr[i], y[i])` points) and vertical lines (to connect `(x[i]+xerr[i], y[i])` and `(x[i+1]-xerr[i+1], y[i+1])` points).

**Comment by sbinet** [comment]
item 2) SGTM.

**Comment by rmadar** [comment]
OK. I can try have a look but probably need some help/guidance on how/where this implementation should be done exactly. Should we put this plotting behavior in `hplot.Add(s)` function or in `hplot.NewS2D()`?

**Comment by sbinet** [comment]
the way I'd go with it (subject to be refined as the plot thickens or unfold, puns intended), would be the following:

- add a new functional option, say, `WithStepsKind(HiSteps|Steps|FSteps)` (like in gnuplot [steps](https://stackoverflow.com/questions/58697529/gnuplot-how-to-stop-histeps-from-terminating-to-zero-y-0-at-start-and-endp))
  https://github.com/go-hep/hep/blob/master/hplot/s2d.go#L102

- handle it in the `withBand()` method (probably `switch`-ing on the value of this newly added `steps` field value, between various ways of creating the `top` and `bot(tom)` "perimeter" lines)
  https://github.com/go-hep/hep/blob/master/hplot/s2d.go#L77

**Comment by sbinet** [comment]
and introducing a new `type`:
```go
type StepsKind byte

const (
    NoSteps StepsKind = iota
    HiSteps
    Steps
    FSteps
)
```

that would be used in `S2D`:
```go
type S2D struct {
    ...
    Band *Band

    // with some nice doc
    steps StepsKind
}
```

**Comment by rmadar** [comment]
OK thanks. They are few things I am not familiar with, so I'll need to sit down and look at it in details, with one (or many) coffee(s). I'll give a shot.

**Comment by sbinet** [comment]
ok. feel free to post questions here.

FYI, `iota` is explained [there](https://github.com/golang/go/wiki/Iota).

**Comment by rmadar** [comment]
I am trying to implement the above suggestion and I'd like to make sure I am in going in the good direction. These are the step I'll plan to follow:
 1. `options.go`: add `WithStepKind(step StepsKind)` and add a field of type `StepsKind` (to be defined in `options.go too, I guess) in the `config` structure ; 
 2. `s2d.go`: add a field of type `StepsKind` to `S2D` structure, initialize it properly given the passed option, and modify the band definition accordingly

The part which is unclear to me is where should I implement the actual step plotting? I guess it should be in `func (pts *S2D) Plot()` ... Maybe I could use the following replacing `data` by a new set of `(x, y)`'s drawing the steps?

```go
if pts.LineStyle.Width > 0 {                                             
             data, err := plotter.CopyXYs(pts.Data)                           
             if err != nil {                                                  
                     panic(err)                                               
             }                                                                
             line := plotter.Line{
                     // --> replace by a new set of data which would draw the steps ?
                     XYs: data,
                     LineStyle: pts.LineStyle,
             }                                                                
             line.Plot(c, plt)                                                
     }
```

**Comment by sbinet** [comment]
yes, the magic of drawing all "plotters" happens in `Plot(draw.Canvas, *plot.Plot)`.

and, yes, I suspect `switch`-ing on the new `stepskind` value, modifying the `plotter.XYs` accordingly and passing it down to `line.Plot` is an effective strategy.
