### ISSUE TITLE
f64s: add a function Take(indices[]int)?

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#671]
I think having a function that return a sub-array corresponding to a slice of indices would be useful - especially in association with `floats.Find()`. This would imply to allocate, so I think it cannot be done in `gonum/floats` package. But we could do it in `f64s`. 

This would typically generalize easy filtering of a given slice, say `s1`, using another slice `s2`:
```go
filtered_slice := f64s.Take(s1, floats.Find(s2, cond))
```

What do you think?

**Comment by sbinet** [comment]
SGTM.

it should probably have that kind of signature (to allow for user-defined allocations):
```go
func Take(dst, src []float64, indices []int) []float64 { ... }
```
