### ISSUE TITLE
Legend improvements

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#683]
Now we have the nice band feature for histogram (which actually don't show up in the legend right now) , I think we should revisit a bit the legend for `H1D`. I would propose something like this (let me now if this is feasible or not), at least for cases without `fill` and with `fill` but no markers.

| line  | fill  |  marker  | band  | legend thumb.|
|---|---|---|---|---|
|  1 | 0  | 0/1  | 0/1  |  sky-line w/ marker, w/ box for the band |
|  0/1 |  1 | 0  | 0  | box w/ or w/o a line around (not the current sky-line - that I know I have asked for) |

I am aware that cases like `fill+markers` would then look strange (a box with a line around and a marker in the middle), as well as `fill+band` which would be even not defined (since the same box would have to carry two colors). But these configuration shouldn't be selected in principle (at least I wouldn't use them).

**Comment by sbinet** [comment]
it certainly is doable.
tentatively assigning it to you :)

**Comment by rmadar** [comment]
Thinking about this again, I think we should also probably add a legend for a band (individually, I mean). So Edited the title of the issue and the different points to address would be:
 - [ ] add a thumbnailer for band 
 - [ ] add band in the thumbnail of `H1D` (not present right now)
 - [ ] tune the thumbnail style of `H1D` depending on the option (band, marker, fill, line, etc ...)
