### ISSUE TITLE
Export ybars and xbars fields for S2D?

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#684]
The goal would be to be able to tune the error bars plotting style, as for histogram `H1D` (*via* `h1d.YErrs`). I guess this would be immediate by exporting `ybars` and `xbars`, but they might be not exportable for a reason (?).

**Comment by sbinet** [comment]
no reason except for always trying to reduce the amount of things to make public.

**Comment by sbinet** [comment]
(ok to export those.)
