### ISSUE TITLE
groot/rtree: idea to improve FormulaFunc in most usual cases

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#719]
Following the discussion from https://github.com/go-hep/hep/pull/691, in particular https://github.com/go-hep/hep/pull/691#issuecomment-623417475, I was trying to think how to remove `reflect` calls. Maybe we could reasonably remove at least one (maybe two) call(s) by specifying the returned type of the user function?

What's about few specific types of `rtree.FormulaFunc` for, says, `float64`, `int64` and `bool` (on top on the generic `FormulaFunc`)? This would allow to only use `reflect` for the function inputs, right? I don't know what would be the perf improvement of such a thing ... But that wouldn't make think more complicated:
```go
fF64 := rtree.FormulaFuncF64(vars, func(...) float64)
fI64 := rtree.FormulaFuncI64(vars, func(...) int64)
fBool := rtree.FormulaFuncBool(vars, func(...) bool)
```

What do you think, is that worth trying?

**Comment by sbinet** [comment]
> What do you think, is that worth trying?

sure.

but I think that most of this is already handled by [that code](https://github.com/go-hep/hep/blob/v0.27.0/groot/rtree/formula.go#L68...L152).
I could be wrong, of course. (I haven't had all the needed morning coffee to be completely confident).

another possible source of inspiration for strategies would be to look at code in [database/sql](https://godoc.org/database/sql) and/or in packages implementing the interfaces of that package.
they have the same issue: how to reliably (and in a performant fashion) expose data (in a type-safe way) to client code so they can call/read stuff from the underlying database.

**Comment by sbinet** [comment]
ok. I had an idea yesterday.
for user functions like:
- `func() float64`
- `func(x1 float64) float64`
- `func(x1, x2 float64) float64`
- `func(x1, x2, x3 float64) float64`

I could come up with these improvements:
```
 benchstat ref.txt new.txt 
name                   old time/op    new time/op    delta
FormulaFunc/f0/Eval-4     247ns ± 3%      25ns ± 3%   -89.97%  (p=0.000 n=20+20)
FormulaFunc/f0/Func-4     238ns ± 3%       4ns ± 2%   -98.19%  (p=0.000 n=20+20)
FormulaFunc/f1/Eval-4     321ns ± 2%      24ns ± 6%   -92.38%  (p=0.000 n=20+19)
FormulaFunc/f1/Func-4     313ns ± 2%       5ns ± 4%   -98.41%  (p=0.000 n=20+20)
FormulaFunc/f2/Eval-4     325ns ± 7%      26ns ± 2%   -91.93%  (p=0.000 n=16+20)
FormulaFunc/f2/Func-4     313ns ± 4%       5ns ± 4%   -98.35%  (p=0.000 n=20+20)
FormulaFunc/f3/Eval-4     322ns ± 4%      25ns ± 5%   -92.17%  (p=0.000 n=20+19)
FormulaFunc/f3/Func-4     313ns ± 2%       6ns ± 4%   -98.05%  (p=0.000 n=18+20)

name                   old alloc/op   new alloc/op   delta
FormulaFunc/f0/Eval-4     40.0B ± 0%      8.0B ± 0%   -80.00%  (p=0.000 n=20+20)
FormulaFunc/f0/Func-4     40.0B ± 0%      0.0B       -100.00%  (p=0.000 n=20+20)
FormulaFunc/f1/Eval-4     48.0B ± 0%      8.0B ± 0%   -83.33%  (p=0.000 n=20+20)
FormulaFunc/f1/Func-4     48.0B ± 0%      0.0B       -100.00%  (p=0.000 n=20+20)
FormulaFunc/f2/Eval-4     48.0B ± 0%      8.0B ± 0%   -83.33%  (p=0.000 n=20+20)
FormulaFunc/f2/Func-4     48.0B ± 0%      0.0B       -100.00%  (p=0.000 n=20+20)
FormulaFunc/f3/Eval-4     48.0B ± 0%      8.0B ± 0%   -83.33%  (p=0.000 n=20+20)
FormulaFunc/f3/Func-4     48.0B ± 0%      0.0B       -100.00%  (p=0.000 n=20+20)

name                   old allocs/op  new allocs/op  delta
FormulaFunc/f0/Eval-4      2.00 ± 0%      1.00 ± 0%   -50.00%  (p=0.000 n=20+20)
FormulaFunc/f0/Func-4      2.00 ± 0%      0.00       -100.00%  (p=0.000 n=20+20)
FormulaFunc/f1/Eval-4      2.00 ± 0%      1.00 ± 0%   -50.00%  (p=0.000 n=20+20)
FormulaFunc/f1/Func-4      2.00 ± 0%      0.00       -100.00%  (p=0.000 n=20+20)
FormulaFunc/f2/Eval-4      2.00 ± 0%      1.00 ± 0%   -50.00%  (p=0.000 n=20+20)
FormulaFunc/f2/Func-4      2.00 ± 0%      0.00       -100.00%  (p=0.000 n=20+20)
FormulaFunc/f3/Eval-4      2.00 ± 0%      1.00 ± 0%   -50.00%  (p=0.000 n=20+20)
FormulaFunc/f3/Func-4      2.00 ± 0%      0.00       -100.00%  (p=0.000 n=20+20)
```

the same could be done for other funcs:
- `func() bool`
- `func(x1 float64) bool`
- `func(x1, x2 float64) bool`

(I guess we could stop at an arity of 10)

and leave the "slow" path for other functions (especially those with mixed signatures such as `func(x1 int32, x2 float64, x3 float32) float64`).

then re-introduce the `rtree.Reader.Formula` method with a slight modification:

```go
func (r *Reader) Formula(fct Formula) (FormulaFunc, error) { ... }
```

where `Formula` is an interface:
```go
type Formula interface {
    RVars() []string // name of the needed branches/rvars
    Bind(rvars []ReadVar)
    Eval() interface{} // this one could be drop actually.
    Func() interface{}
}
```
so users could implement that interface and get the same type of perf gains for their own function signatures.

(ok. writing this down, I realize a better solution would be for the `Formula` and `FormulaFunc` types to live in their own little package, say `groot/rtree/rfunc`)

**Comment by sbinet** [comment]
(thanks for encouraging me to find a better solution than what I came up with initially.
turns out the better solution was involving proper interfaces. "who knew?" :P)

**Comment by rmadar** [comment]
A factor 10!! That is something ! I think it's really cool and the possibility to have the same perf for any function signature (to be implemented by the user) is just great!

**Comment by sbinet** [comment]
see #728 for the actual implementation (together with an example of a user-provided implementation of a `rfunc.Formula`, in the `ExampleReader_withFormulaFromUser` function)

**Comment by rmadar** [comment]
I have started to look at it for the user-defined functions, the syntax is really a good compromise between verbosity, flexibility and perf!

It was mentioned a set of predefined functions for most usual signatures and output types. I guess this is what is being worked out in https://github.com/go-hep/hep/issues/729? This just to know and not re-defined what already exist.

Out of curiosity: did you happen to compare the speed of this new approach with its 5ns/op with the 'traditional' ones (with explicit go function and variable loading)?

**Comment by sbinet** [comment]
#729 is about a somewhat nicer way to generate the predefined functions.

but it's just about that (and a tool people could invoke on their code base to generate their functions: the implementation is really very mechanical)

the functions have already been generated:
- https://github.com/go-hep/hep/blob/master/groot/rtree/rfunc/rfunc_float64_gen.go
- https://github.com/go-hep/hep/blob/master/groot/rtree/rfunc/rfunc_float32_gen.go
- https://github.com/go-hep/hep/blob/master/groot/rtree/rfunc/rfunc_bool_gen.go

happy to generate some more though.

**Comment by rmadar** [comment]
Yes, I saw those but I found only non exportable fields ... Maybe I missed the proper ones. It might helpful to add an example or two with the pre-defined `rfunc.Formula` - unless it's already in the doc and I missed it!

**Comment by sbinet** [comment]
thanks to _e.g._ this line:
https://github.com/go-hep/hep/blob/master/groot/rtree/rfunc/rfunc_float64_gen.go#L26
```
func init() {
	funcs[reflect.TypeOf(funcAr00F64{}.fct)] = newFuncAr00F64
}
```

and those:
https://github.com/go-hep/hep/blob/master/groot/rtree/rfunc/rfunc.go#L35...L50
```go
type newFunc func(rvars []string, fct interface{}) (Formula, error)

var (
	funcs = make(map[reflect.Type]newFunc)
)

// New returns a new formula from the provided list of needed tree variables
// and the provided user function.
func New(rvars []string, fct interface{}) (Formula, error) {
	typ := reflect.TypeOf(fct)
	mk, ok := funcs[typ]
	if ok {
		return mk(rvars, fct)
	}
	return newGenericFormula(rvars, fct)
}
```

the pre-defined functions are automagically used via a call to `rfunc.New(...)`.
(with a fallback on the `reflect`-based code for those that don't have a fast implementation)

as for an example on how to implement `rfunc.Formula`, it's done here:
https://github.com/go-hep/hep/blob/master/groot/rtree/example_reader_test.go#L283...L313
and used there:
https://github.com/go-hep/hep/blob/master/groot/rtree/example_reader_test.go#L375

> Out of curiosity: did you happen to compare the speed of this new approach with its 5ns/op with the 'traditional' ones (with explicit go function and variable loading)?

I haven't performed such a comparison.
but 5ns/op is pretty darn fast and is also kind of the order of magnitude for calling regular Go functions.

**Comment by rmadar** [comment]
hoooo this is *automatically* done ... wonderful!

**Comment by rmadar** [comment]
OK I have implemented a small benchmark comparing the perf of these new `rtree.Formula` wrt to the direct reading, and I am quite surprised (at this stage, I'd bet for a bug on my side). Basically, I am still much slower than a "direct call" (and this difference increases with the number of variables). I am using mostly `func (float64) float64`, `func (float32) float64` or `func (bool) bool` functions so it should should use the optimized approach, right?

You can reproduce the plot below with https://github.com/rmadar/tree-gonalyzer/commit/94e71ddc3d8cfcb9594e20ff2a9391473ba514fc#diff-eadab76df62bc1367db626c39bb34bef . 

![image](https://user-images.githubusercontent.com/30081646/83032363-058c9980-a036-11ea-8d92-5bc52b06ec44.png)

(I guess the legend/labels are relatively self-explanatory but let me know if something is unclear).

**Comment by rmadar** [comment]
Ha !!!! this is the `func (float32) float64` which is not implemented probably ...

Running only over `func (float64) float64`, it is the same order of magnitude!!! Note that my 'no formula' is a bit slower because it's not well written (there are some type assertion for every event ...).

![image](https://user-images.githubusercontent.com/30081646/83035384-ac266980-a039-11ea-8d44-bff65be201ce.png)

I'll fully switch to the new `rtree.Formula` then ! That's great!!!

(I might open an issue with few more signature/types to implement, at some point)

**Comment by sbinet** [comment]
cool.
yeah, see, the automagical thingy is already proven a bit treacherous.
I've removed it in https://github.com/go-hep/hep/pull/734

please comment on that PR for signatures to be added.
