### ISSUE TITLE
groot/rtree: speed lost between two commits

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#740]
Apparently, there is a significant speed lost (~ x 5) between two https://github.com/go-hep/hep commits. I didn't change my code at all for these test, just:
```
go get -u -v go-hep.org/x/hep@commit
go run ./main
```
(using https://github.com/rmadar/tree-gonalyzer/tree/master/ana-perf)

### Old commit:  e1d8871a38f083a660783cf5d7419da8a872eb40

![image](https://user-images.githubusercontent.com/30081646/83258883-5e377000-a1b7-11ea-884d-3cfa4bbe8654.png)

### Current master: 4d1e5f0811fbe1bbe4b07393e4c70822c14c026d

![image](https://user-images.githubusercontent.com/30081646/83259038-a48ccf00-a1b7-11ea-9b53-422c140ea33a.png)

**Comment by sbinet** [comment]
probably it's because before the (real) fix for #736, `rtree.Reader` wasn't actually reading all the data.
depending on the number of branches that had the same problem than in #736 and their size, ... it could explain the effect you see.

**Comment by rmadar** [comment]
Maybe I should have said that the perf above only used non-slice data. Does that change the picture?

**Comment by sbinet** [comment]
I was perusing your code and indeed noticed the variables you declare aren't bound to `[]T`...
ok. back to a nice debugging session :)

**Comment by sbinet** [comment]
isn't this because of the use of a non-specialized formula-func?
```
* 4d1e5f08 groot/rtree: fix handling of rleaf-element with a "This" StreamerSTL
* 5e981213 groot/rtree: add formula test for slices
* 351d7f17 groot: add support for extracting copyright year from code templates
* c771d0c9 groot/cmd/root-gen-rfunc: first import
* e1d8871a hplot: fix HStack band display logic
```
between `e1d8871a` and `4d1e5f08`, there's `c771d0c9` that removed the automagic registration of formula-funcs.

**Comment by sbinet** [comment]
yep:
```
2020/05/29 15:34:03 warning: slow formula for []string{"truth_dphi_ll"} (fct=func(float64) float64)
2020/05/29 15:34:03 warning: slow formula for []string{} (fct=func() float64)
2020/05/29 15:34:03 warning: slow formula for []string{} (fct=func() bool)
```

**Comment by rmadar** [comment]
Hum, but I thought `func(float64) float64` was there, same for the two others:
 + F64 -> F64: https://godoc.org/go-hep.org/x/hep/groot/rtree/rfunc#F64Ar1
 + None -> F64: https://github.com/go-hep/hep/blob/master/groot/rtree/rfunc/rfunc_f64_gen.go#L14
 + None -> B: https://godoc.org/go-hep.org/x/hep/groot/rtree/rfunc#PredF32Ar0

OK maybe I miss understood. I need to look a bit more into these default functions (and actually add them).

Btw, how to access the info whether the good functions are defined or not (I mean in the code)?

**Comment by sbinet** [comment]
here is the beginning of a fix (on your side):
```diff
diff --git a/ana/treefunc.go b/ana/treefunc.go
index 6ed2dad..ac868fc 100644
--- a/ana/treefunc.go
+++ b/ana/treefunc.go
@@ -154,7 +154,20 @@ func NewVarI32s(v string) TreeFunc {
 // FormulaFrom returns the rtree.FormulaFunc function associated
 // to the TreeFunc f, from a give rtree.Reader r.
 func (f *TreeFunc) FormulaFrom(r *rtree.Reader) rfunc.Formula {
-       ff, err := r.FormulaFunc(f.VarsName, f.Fct)
+       var (
+               ff  rfunc.Formula
+               err error
+       )
+       switch fct := f.Fct.(type) {
+       case func(float64) float64:
+               ff = rfunc.NewF64Ar1(f.VarsName, fct)
+       default:
+               ff, err = rfunc.NewGenericFormula(f.VarsName, f.Fct)
+               if err != nil {
+                       log.Fatalf("could not create formula func: %+v", err)
+               }
+       }
+       ff, err = r.Formula(ff)
        if err != nil {
                log.Fatalf("could not create formulaFunc: %+v", err)
        }
```

(perhaps a better fix would to add a private field to `TreeFunc` that's a `rfunc.Formula`, left `nil` for non-specialized formulae, instead of re-doing the type-switch...)

**Comment by rmadar** [comment]
Haaa ok so now pre-defined are not loaded automatically... I missed this somehow (and few of your comments about "automagical" stuff make sense now). Thanks, I am closing the issue.

**Comment by sbinet** [comment]
perhaps keeping the `rtree.Reader.FormulaFunc(...)` API was a mistake?
should we just drop it and ask users to replace:
```go
form, err := r.FormulaFunc(branches, usrFct)
```

with:
```go
form, err := rfunc.NewGenericFormula(branches, usrFct)
check(err)
form, err = r.Formula(form)
check(err)
```

?
this would perhaps reduce confusion down the line...

**Comment by rmadar** [comment]
After thinking about it, I think you're right. We could have:
```
rfct := rfunc.New(branches, usrFct) // generic (slow) 
rfct := rfunc.FtoD(branches, usrFct) // F32->F64 pre-defined (fast) 
... 
```

Then for user `rfunc`, this would look like:
```
userRfct := &myDef { ... } // fast
```

I have notices that the user side of `myDef` is the same as my `TreeFunc`, which is at the end, what is needed (I think). So it might go in the right direction, at least for the next iteration ;-)

**Comment by rmadar** [comment]
we could even reintroduce the automatic loading of pre-defined functions with something like:
```
rfrc := rfuncNewAuto(branches, userFct) 
```

This would keep this nice feature (for common and quick use-cases), while making it explicit to the user that something automagical is happening behind the scene.

**Comment by sbinet** [comment]
I don't think we can re-introduce the automatic loading of the non-reflect-based formula funcs w/o preventing the Go compiler/linker from removing the unused formula-funcs types from the final binary.

for the moment, I suspect helping the linker won't save much, but it's the kind of slippery slope that get's you to "bloated C++" :P 

at the moment, we have:
```go
form, err := rfunc.NewGenericFormula(branches, fct)
form := rfunc.NewF64Ar1(branches, func(x float64)float64{ return 2*x} )
```

so, save the naming convention that would need to be implemented, I think we're (almost already) inline with what you've proposed above.

**Comment by rmadar** [comment]
OK I am not sure to fully understand the business of binaries, links and so on but what I had in mind (and I a plan to implement in my tool) is something like:
```go
func NewAuto(branches, fct) (func.Formula) {
  switch fct.(type) {
  case func() float64:
     return toD(branches, fct)
  case func(float32) float64:
    return FtoD(branches, fct)
  ...
 default:
   return NewGenericFormula(branches, fct)
}
```
I guess it would not work around the issue you mentioned above (if possible at all?)

**Comment by sbinet** [comment]
yes, that's (more or less, see: [here](https://github.com/go-hep/hep/blob/1b6e3cf34a85c97ff4cf1be3a61a7c8a8d995ef7/groot/rtree/rfunc/rfunc.go#L35...L50) and [there](https://github.com/go-hep/hep/blob/1b6e3cf34a85c97ff4cf1be3a61a7c8a8d995ef7/groot/rtree/rfunc/rfunc_float32_gen.go#L14...L27)) how originally the `rfunc.New` function was implemented.
I believe it's fine to push it into user code: _they_ know the set of functions _they_ want to be able to use for a given workload.

I'd argue doing the same thing in `rtree/rfunc` makes less sense b/c: where do you draw the line b/w what is sensible for application-A and what's sensible for application-B.
you'd end up with the whole set of possible functions/formulae.

that said, in a couple of years, it might be a completely moot point **if** generics are accepted into Go, in some form, such as: https://github.com/golang/go/issues/15292

**Comment by rmadar** [comment]
Yes, I understand and I think indeed it's fair.

Maybe one other **minor** point on `reader.Formula()`, related to "readability": currently this function takes the same object (well, *type*) as input and output, which is called `rfunc.Formula`. In the doc, it reads we need to do something like:
```go
formA := reader.Formula(FormB) // where FormA and FormB are the *same* type
```
So the "only" difference between `formA` and `formB` is that one is bound to the reader, while this other is not. I thought maybe it might be easier to understand the mechanics, if `formA` and `formB` were from two different types. Schematically, `formA = formB + reader bounding`, so I would find this kind of syntax more intuitive:

**Comment by sbinet** [comment]
We could indeed have a 'rtree.Formula' interface that would be the same then the 'rfunc.Formula' one without the 'Bind' method.
And have the 'rtree.Reader' return the 'rtree.Formula' one.

**Comment by sbinet** [comment]
'Reader.Formula' documentation probably deserves a bit of polishing.
