### ISSUE TITLE
hplot: handle hstack+band with empty bins

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#751]
to fix #749 , we introduced "empty bins" for the bands that display error bars, in a log-y environment.

we need to come up with a new way to handle colored/filled error bar "boxes" as this "connects" 2 bins (separated by an empty bin).
see:

![img](https://github.com/go-hep/hep/raw/24781f7c/hplot/testdata/hstack_logy_golden.png)

**Comment by rmadar** [comment]
I think we could try to send the problematic bin to zero for the band as well. But of course, if we don't want to destroy the band in the two bins around the problematic one, we have to find a "trick". 

One idea could be to add two points on right of `i-1` bins and two points on the left of the `i+1` bins, with  the following x values: `xHighEdge[i-1]+epsilon` and `xLowEdge[i+1]-epsilon`. These four points would have `y=0`. Actually, I even wonder if we could take `epsilon=0` ...

OK, one has probably to try to see how it looks. If you think it's good-enough idea (this is still a bit dirty so ...), I can give a shot.
