### ISSUE TITLE
xrootd: close.Client() doesn't work?

### ISSUE THREAD

**Issue by kiderrien** [go-hep/hep#776]
hello 

When I use xrd-cp from xrootd/cmd, I have TIME_WAIT at the end. 

```
[ xrd-cp]$ netstat -t  | grep TIME_WAIT | wc -l
0
[ xrd-cp]$ go run main.go root://localhost//tmp/test3 /tmp/doc
[ xrd-cp]$ netstat -t  | grep TIME_WAIT | wc -l
2
```

I have the same problem with scripts.

When I look at the client's content before and after a close, we get the same result.
```
defer fmt.Println(client)
defer client.Close()
defer fmt.Println(client)
```
Same observation with the files before and after a close.

I'm not sure but I have the impression that the client is not closed with a client.Close ().

**Comment by sbinet** [comment]
it's a normal state of the TCP connection (and actually does tell you the client _is_ closed).
see:
- https://9oelm.github.io/2018-05-06--Listening,-Established,-Close_wait-and-Time_wait-in-netstat/

with this patch, though, the number of `TIME_WAIT`s dramatically reduces:
```diff
diff --git a/xrootd/session.go b/xrootd/session.go
index f196364f..efe31439 100644
--- a/xrootd/session.go
+++ b/xrootd/session.go
@@ -20,6 +20,14 @@ import (
        "go-hep.org/x/hep/xrootd/xrdproto/sigver"
 )
 
+func setupConn(c net.Conn) {
+       conn, ok := c.(*net.TCPConn)
+       if !ok {
+               return
+       }
+       _ = conn.SetLinger(0)
+}
+
 // cliSession is a connection to the specific XRootD server
 // which allows to send requests and receive responses.
 // Concurrent requests are supported.
@@ -86,6 +94,7 @@ func newSession(ctx context.Context, address, username, token string, client *Cl
                cancel()
                return nil, err
        }
+       setupConn(conn)
 
        sess := &cliSession{
                ctx:       ctx,
@@ -454,6 +463,7 @@ func newSubSession(ctx context.Context, parent *cliSession) (*cliSession, error)
                cancel()
                return nil, err
        }
+       setupConn(conn)
 
        sess := &cliSession{
                ctx:       ctx,
```

that said, it has some unwanted effects on other parts of any long-living `xrootd.Client` (ie: a client receiving a late packet)

FWIW, the C++ xrootd client also produces `TIME_WAIT`.

how do you manage `xrootd.Client`s ? one per file? one per server?
IIRC, `xrootd.Client` is supposed to multiplex connections (so one should only have one per connection to a server).

**Comment by kiderrien** [comment]
Thank you for these precisions.
Indeed I open too much connection (1 per file and 1 to check the checksum the file).
I will review my code to reduce the number of connections.

**Comment by sbinet** [comment]
ok.

let me close this issue, then.
(but feel free to re-open or send another one anew if things go awry)
