### ISSUE TITLE
groot: corrupted output file for large input dataset

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#782]
I am running a go program over very large ROOT files. I tried to split jobs into group of file list containing a total of 6.5 millions events and the produced ROOT file has a size of ~ 2Go. The go program ran perfectly, without any error but when I tried to open the ROOT file with ROOT, I got:
```
> root ttbar00.root 
root [0] 
Attaching file ttbar00.root as _file0...
Warning in <TFile::Init>: file ttbar00.root probably not closed, trying to recover
Error in <TString::ReadBuffer>: found case with nwh=255 and nchars=-8856916
Info in <TFile::Recover>: ttbar00.root, recovered key TTree:Zc:0\ufffd at address 2663167383
Info in <TFile::Recover>: ttbar00.root, recovered key TDirectoryFile:ttbar at address 2666817087
Warning in <TFile::Init>: successfully recovered 2 keys
(TFile *) 0x51a58e0
```

While the same output for an input file list of 2 MEvts looks like this:
```
Attaching file ttbar00.root as _file0...
(TFile *) 0x3b879f0
root [1] .ls
TFile**		ttbar00.root	
 TFile*		ttbar00.root	
  KEY: TTree	nominal;1
```

I have no idea how you would like to proceed to debug this (and if this is worth it), but I thought it could be useful to mention this issue - at least.

**Comment by sbinet** [comment]
if you could place the corrupted file somewhere I could retrieve it that'd be great.
(I won't be able to download it just yet, though...)

**Comment by sbinet** [comment]
(I suspect this is the switch from "small files" to "big files" (ie: some ROOT header needs to switch a few fields from int32 to int64 to handle file positions bigger than 2Gb))

**Comment by rmadar** [comment]
OK! Here is the link of this large file: https://cernbox.cern.ch/index.php/s/qRs80pT9R7yU6rd
