### ISSUE TITLE
hplot: issue with unknown (default) font

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#787]
Trying to use Latex-compiled plot, I have this panic message:
```
panic: Unknown font: HelveticaHe.  Available fonts are: Courier-BoldOblique Helvetica-Oblique Times-Roman Courier Courier-Oblique Helvetica Helvetica-Bold Helvetica-BoldOblique Times-Bold Times-Italic Times-BoldItalic Courier-Bold

goroutine 4158 [running]:
go-hep.org/x/hep/hplot.New(0x0)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200622082015-aa37c691264e/hplot/plot.go:32 +0x455
github.com/rmadar/tree-gonalyzer/ana.(*Maker).plotVar(0xc000001800, 0x8, 0x3, 0xf31b00, 0xc001434000)
	/users/divers/atlas/madar/home2/tree-gonalyzer/ana/varplotter.go:92 +0x64
github.com/rmadar/tree-gonalyzer/ana.(*Maker).concurrentPlotVar(0xc000001800, 0x8, 0x3, 0xf31b00, 0xc001434000, 0xc0000e4020)
	/users/divers/atlas/madar/home2/tree-gonalyzer/ana/varplotter.go:82 +0x93
created by github.com/rmadar/tree-gonalyzer/ana.(*Maker).PlotVariables
	/users/divers/atlas/madar/home2/tree-gonalyzer/ana/varplotter.go:58 +0x1c5
```

Following the error in the code, I ended-up on this piece of code with an interesting comment :)
https://github.com/go-hep/hep/blob/7d2c4375757af53248d48153cbd1610499168b5a/hplot/plot.go#L29-L33

I guess I am doing something strange (or maybe the font is not installed on the machine I run on) ... Sorry if that's the case!

**Comment by sbinet** [comment]
Isn't there a typo? (ie: "HelveticaHe" instead of the correct "Helvetica" ?)

**Comment by rmadar** [comment]
Yes, this is what I think but the thing is that I don't specify this `HelveticaHe` anywhere in my code. So I guess the typo is somewhere else - if that's possible?

**Comment by sbinet** [comment]
I'll have a look (when brain can work, so when below 30°C).

Do you have a (somewhat) minimal reproducer?

**Comment by rmadar** [comment]
OK, it was "my" latex setup, sorry for the fake issue! I'll close it.
