### ISSUE TITLE
hplot: handling negative bin content in log scale

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#788]
Recently, I came across a `panic` message with a log-scale histogram having a very low stat and negative weights - as discussed in https://github.com/rmadar/tree-gonalyzer/issues/47. Looking `hplot` code more closely, I think it might be to replace this

https://github.com/go-hep/hep/blob/7d2c4375757af53248d48153cbd1610499168b5a/hplot/h1d.go#L203

with 
```go
 ylow := math.Inf(+1) // ylow will hold the smallest *positive* y value. 
```

I'll try to submit a PR on this. If I am right, this modification might be relevant for all other plotters having the `LogY` option, namely `BinnedErrBand`, `Function` and `HStack`.

**Comment by sbinet** [comment]
SGTM

**Comment by rmadar** [comment]
I have opened https://github.com/go-hep/hep/pull/789
