### ISSUE TITLE
all: convert to go:build directives

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#798]
as mentioned in https://github.com/golang/go/issues/41184, Go will probably migrate to a more robust build constraints directive, as explained there:
- https://golang.org/s/go-build-design

we should prepare for that:

- [x] for Go-1.17: add all `//go:build` directives
- [x] for Go-1.18: remove all `// +build` directives

**Comment by rsc** [comment]
Please wait until Go 1.17 to add any //go:build directives.
Go 1.16 is only setting up for Go 1.17. Go 1.17 is the real change.

**Comment by sbinet** [comment]
Thanks for pointing this out.
I've modified the planned timeline.
