### ISSUE TITLE
rtree: possibility to implement vector<string> type

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#852]
Hello,

I need to read `TTree` with a branch sucha as:

```
*............................................................................*
*Br    6 :names_mc_generator_weights : vector<string>                        *
*Entries :        4 : Total  Size=      19193 bytes  File Size  =       3880 *
*Baskets :        4 : Basket Size=      32000 bytes  Compression=   4.80     *
*............................................................................*
```

Even if I don't load this branch as a `rtree.ReadVar`, it crashes the file reading with the following message:
```
panic: rtree: unknown streamer element: &rdict.StreamerSTL{StreamerElement:rdict.StreamerElement{named:rbase.Named{obj:rbase.Object{ID:0x0, Bits:0x3000000}, name:"vector<string>", title:""}, etype:500, esize:24, arrlen:0, arrdim:0, maxidx:[5]int32{0, 0, 0, 0, 0}, offset:0, ename:"vector<TString>", xmin:0, xmax:0, factor:0}, vtype:1, ctype:65}
```

Would this errror be easy to fix (or even to work around, in a short timescale)?

Thanks!

**Comment by sbinet** [comment]
could you post your file somewhere?
(if it's too big, you can leave it one of LPC machines)

**Comment by rmadar** [comment]
Thanks. Can you see this `/AtlasDisk/data1/spin_correlation_v2/mc/group.phys-top.410472.PhPy8EG.DAOD_TOPQ1.e6348_s3126_r9364_p4346.AB-21.2.169-MC16aSignalttbar-v04_out_root/group.phys-top.25549891._000001.out.root` ?

**Comment by sbinet** [comment]
yes, I have access to these 3Gb worth of data :)

**Comment by sbinet** [comment]
ok, it seems to work with `v0.28.5`:

```
$> root-ls -t ./testdata/group.phys-top.25549891._000001.out.root >& /dev/null; echo $?
0
```

which version are you using?

**Comment by rmadar** [comment]
I was using `v0.28.4` and it seems to properly work with `v0.28.5` indeed. I am closing the issue. Thanks!

**Comment by sbinet** [comment]
I love it when a bug has been already fixed by my past self.

(when it's been fixed by my futur self as well. 
actually, I also love it when it's been fixed by somebody else, from any timeline.
well, I guess I love it when a bug has been _already_ fixed.)
