### ISSUE TITLE
meta: submit go-hep to JOSS

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#87]
We should consider submitting a paper about `go-hep` to the journal of open source software:

http://joss.theoj.org/about

**Comment by sbinet** [comment]
@mughetto @decibelCooper @Bastiantheone @ebusato 

could you please add your contact infos in `paper.md` so I can submit this to JOSS?

FYI, orcid is https://orcid.org/

**Comment by Bastiantheone** [comment]
To be clear, I just need to add my school as affiliation?

**Comment by sbinet** [comment]
Your school and create an orcid account if not already (and tell us your orcid.)
Thanks.

**Comment by sbinet** [comment]
thanks all for the prompt reactivity.
I know @ebusato is still on holidays. He should be back by the end of August.

**Comment by decibelCooper** [comment]
Nice work, @sbinet

**Comment by sbinet** [comment]
thanks! (BTW: you'll have to share (at some point) the nice LCIO related plots that you've been creating in your repos. much interested in getting some actual HEP research plots :) Perhaps a blog entry on https://go-hep.org?)

**Comment by decibelCooper** [comment]
@sbinet Sure, if you don't mind them being about EIC studies =) (a little disconnected from the HEP community, I think).  I'll keep this in mind next time I'm working on plots.
