### ISSUE TITLE
groot: leverage generics for riofs.File.Get

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#893]
right now (w/ Go < 1.18), to retrieve a value from a `riofs.File` (or anything that supports the `riofs.Directory` interface), one needs to:

```go
obj, err := f.Get("key")
if err != nil {
    panic(err)
}
tree, ok := obj.(rtree.Tree)
if !ok {
    panic(fmt.Errorf("key is not a Tree: %T", obj))
}
```

with generics in Go-1.18, it should be possible to write instead:

```go
tree, err := riofs.Get[rtree.Tree](f, "key")
if err != nil {
    panic(err)
}
// tree is of type rtree.Tree.
```

**Comment by deepto98** [comment]
Hi, can I pick this up?

**Comment by sbinet** [comment]
thanks for the offer.
as can be seen in [branch issue-893](https://github.com/go-hep/hep/compare/main...sbinet-hep:issue-893?expand=1), I've already taken a stab at it.

the main reason as for why I haven't yet merged that branch into `main` is we'd need to decide whether `Go-HEP` drops support for Go-1.17 (and only support Go-1.18) - 6 months ahead of schedule - or create a Go-1.18-dedicated branch where `generics`-based code can live.
indeed, to have `Go-HEP` + `generics` code compile, one needs to specify `go 1.18` in the `go.mod` file.
which will break clients using Go-1.17.
