### ISSUE TITLE
Rename package fwk/testdata (Go reserved name)

### ISSUE THREAD

**Issue by dolmen** [go-hep/hep#941]
`testdata` is a special name for the Go toolchain. `go help packages` says:
> Directory and file names that begin with "." or "_" are ignored by the go tool, as are directories named "testdata".

Package `go-hep.org/x/hep/fwk/testdata` should be renamed to avoid problems.

**Comment by dolmen** [comment]
This issue blocks any further changes I would like to propose to the `fwk` code as files in the `fwk/testdata` package would be affected.

**Comment by sbinet** [comment]
yesh, the code under that `testdata` "fake" package was written before the `"internal"` concept existed.
I guess one could move that code under, say, `"fwk/internal/fwktest"` or something.
WDYT?
